Use python 3.12
3.13 introduces this regression in one of our dependencies:
from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: /usr/local/lib/python3.13/site-packages/_cffi_backend.cpython-313-x86_64-linux-gnu.so: undefined symbol: _PyErr_WriteUnraisableMsg

Signed-off-by: Leonardo Held <leonardo.held@toradex.com>